spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# minio配置
storage:
  minio:
    endpoint: http://localhost:9000
    access-key: 1ung6DUOusSwEsj07ynF
    secret-key: j92V48ZjwChJgqsovlxndqottxDKQGNO6vKOdNCc
    bucket-name: blog
    base-url: http://localhost:9000/blog

